#!/usr/bin/env bash
set -ex
source /opt/conda/etc/profile.d/conda.sh
conda activate ccf_reg

#python -u main.py "$@"
STITCHED="$1"
CHANNEL="$2"
ROTATE="$3"
ADDITIONAL="$4"

python -u main.py --stitched "$STITCHED" --channel "$CHANNEL" --rotate "$ROTATE" --extra "$ADDITIONAL"
