#!/usr/bin/env bash
set -ex
source /opt/conda/etc/profile.d/conda.sh
conda activate ccf_reg

#python -u main.py "$@"
STITCHED="$1"
CHANNEL="$2"
python -u main__.py --stitched "$STITCHED" --channel "$CHANNEL"
