# ------------------- #
#   Stage 1: Builder  #
# ------------------- #
FROM condaforge/miniforge3:latest as builder

ARG DEBIAN_FRONTEND=noninteractive
ENV CONDA_ENV=ccf_reg
ENV PATH=/opt/conda/envs/$CONDA_ENV/bin:$PATH

# Install only what's needed to build packages (temporarily)
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc g++ build-essential && \
    rm -rf /var/lib/apt/lists/*

# Create env and install packages
RUN conda create -n $CONDA_ENV python=3.10 -y && \
    /opt/conda/envs/$CONDA_ENV/bin/pip install -U --no-cache-dir --use-deprecated=legacy-resolver \
    antspyx==0.6.3 \
    argschema==3.0.4 \
    scikit-image==0.19.3 \
    tifffile==2022.10.10 \
    bokeh==3.8.2 \
    zarr==2.13.3 \
    aind-data-schema==2.8.0 \
    "aind-data-schema-models>=5.7.1,<6" \
    psutil \
    dask[distributed]==2026.6.0 \
    cloud-volume[all_codecs]==11.0.2 \
    matplotlib==3.10.9 \
    ome-zarr==0.8.2 \
    natsort==8.4.0 \
    crackle-codec==0.26.0 \
    tensorstore==0.1.72 \
    compresso \
    s3fs \
    boto3 \
    log-schema==0.2.10.dev1 &&
    conda clean --all --yes

# ------------------- #
#   Stage 2: Runtime  #
# ------------------- #
FROM condaforge/miniforge3:latest

LABEL maintainer="Camilo Laiton <camilo.laiton@alleninstitute.org>" \
    org.opencontainers.image.title="Image Atlas Registration" \
    org.opencontainers.image.description="Container for registration of lightsheet images to the Allen CCF V3 atlas" \
    org.opencontainers.image.version="0.0.37" \
    org.opencontainers.image.licenses="MIT"

ENV CONDA_ENV=ccf_reg
ENV PATH=/opt/conda/envs/$CONDA_ENV/bin:$PATH

# Copy env from builder
COPY --from=builder /opt/conda /opt/conda

CMD ["bash"]
