FROM condaforge/miniforge3:latest

# --------------------- #
#      METADATA         #
# --------------------- #
LABEL maintainer="Camilo Laiton <camilo.laiton@alleninstitute.org>" \
      org.opencontainers.image.title="Image Atlas Registration" \
      org.opencontainers.image.description="Container for registration of lightsheet images to the Allen CCF V3 atlas" \
      org.opencontainers.image.version="0.0.31" \
      org.opencontainers.image.licenses="MIT"

ARG DEBIAN_FRONTEND=noninteractive

# --------------------- #
#   SYSTEM DEPENDENCIES #
# --------------------- #
RUN apt-get update && \
    apt-get upgrade -y --no-install-recommends build-essential && \
    apt-get install -y --no-install-recommends gcc g++ && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# --------------------- #
#     CONDA ENV SETUP   #
# --------------------- #
RUN conda create -n ccf_reg python=3.8 --yes && \
    conda clean --all --yes

# --------------------- #
#     ENVIRONMENT PATH  #
# --------------------- #
ENV PATH="/opt/conda/envs/ccf_reg/bin:$PATH"

# Make RUN commands use the new environment:
SHELL ["conda", "run", "-n", "ccf_reg", "/bin/bash", "-c"]

# --------------------- #
#     PYTHON PACKAGES   #
# --------------------- #
RUN pip install -U --no-cache-dir \
    antspyx==0.4.2 \
    argschema==3.0.4 \
    s3fs==2022.11.0 \
    scikit-image==0.19.3 \
    tifffile==2022.10.10 \
    bokeh==2.4.2 \
    zarr==2.13.3 \
    aind-data-schema==1.0.0 \
    xarray_multiscale==1.1.0 \
    dask[distributed]==2022.11.1 \
    cloud-volume[all_codecs]==11.0.2 \
    matplotlib==3.7.3 \
    ome-zarr==0.8.2 \
    natsort==8.4.0 \
    crackle-codec==0.26.0 \
    aicsimageio@git+https://github.com/camilolaiton/aicsimageio.git@feature/zarrwriter-multiscales-daskjobs \
    awscli
